image: gitpod/workspace-yugabytedb-preview

tasks:
  - name: 1a-ybdb
    env:
      HOST_LB: "127.0.0.1"
      HOST_LB2: "127.0.0.2"
      HOST_LB3: "127.0.0.3"
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --advertise_address=$HOST_LB --cloud_location=ybcloud.ap-south-1.ap-south-1a --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB --cloud_location=ybcloud.ap-south-1.ap-south-1b --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB --cloud_location=ybcloud.ap-south-1.ap-south-1c --fault_tolerance=zone
      yugabyted configure data_placement --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --fault_tolerance=zone
  - name: 1b-ysqlsh
    command: |
      gp ports await 5433
      sleep 5
      ysqlsh
  - name: 2a-install-jvm
    init: |
      echo y | sdk install java 17.0.6-librca || true
      gp sync-done jvm-17
  - name: 2b-spring-boot
    init: |
      gp sync-await jvm-17
      gradle assemble -x test
    command: |
      gp ports await 5433
      gradle test

# exposed ports
ports:
  - port: 8080
    name: spring-boot
    onOpen: ignore
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 15433
    name: yugabyted-ui
    onOpen: ignore

